repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.12.0
    hooks:
      - id: yamlfix
        args:
          - -c
          - .yamlfix.toml
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.78.1
    hooks:
      - id: cfn-lint
        files: infrastructure/.*/(template.yaml)$
  - repo: https://github.com/bridgecrewio/checkov
    rev: 2.3.329
    hooks:
      - id: checkov_diff
        entry: checkov --framework cloudformation -f
