AWSTemplateFormatVersion: '2010-09-09'

Description: |
  Creates the necessary DNS records, certificates and domain names for the shared signals account

Parameters:
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - build
      - staging
      - integration
      - production

Conditions:
  IsProduction: !Equals
    - !Ref Environment
    - production
  MockReceiverCustomDomain: !Or
    - !Equals
        - !Ref Environment
        - build
    - !Equals
        - !Ref Environment
        - staging

Resources:
  ##################
  # Mock Receiver  #
  ##################

  SharedSignalsMockReceiverApiCertificate:
    Condition: MockReceiverCustomDomain
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub shared-signals-mock-receiver.transaction.${Environment}.account.gov.uk
      DomainValidationOptions:
        - DomainName: !Sub shared-signals-mock-receiver.transaction.${Environment}.account.gov.uk
          HostedZoneId: !ImportValue SharedSignalsMockReceiverApiPublicHostedZoneId
      ValidationMethod: DNS

  SharedSignalsMockReceiverApiDomainName:
    Condition: MockReceiverCustomDomain
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Sub shared-signals-mock-receiver.transaction.${Environment}.account.gov.uk
      EndpointConfiguration:
        Types:
          - REGIONAL
      RegionalCertificateArn: !Ref SharedSignalsMockReceiverApiCertificate
      SecurityPolicy: TLS_1_2

  SharedSignalsMockReceiverApiAliasRecord:
    Condition: MockReceiverCustomDomain
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt SharedSignalsMockReceiverApiDomainName.RegionalDomainName
        EvaluateTargetHealth: false
        HostedZoneId: !GetAtt SharedSignalsMockReceiverApiDomainName.RegionalHostedZoneId
      HostedZoneId: !ImportValue SharedSignalsMockReceiverApiPublicHostedZoneId
      Name: !Ref SharedSignalsMockReceiverApiDomainName
      Type: A

  SharedSignalsMockReceiverApiDomainNameParameter:
    Condition: MockReceiverCustomDomain
    Type: AWS::SSM::Parameter
    Properties:
      Name: SharedSignalsMockReceiverApiDomainName
      Type: String
      Value: !Ref SharedSignalsMockReceiverApiDomainName

  ############
  # SSF API  #
  ############

  SharedSignalsTransmitterApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !If
        - IsProduction
        - shared-signals-transmitter.transaction.account.gov.uk
        - !Sub ssf-transmitter.transaction.${Environment}.account.gov.uk
      DomainValidationOptions:
        - DomainName: !If
            - IsProduction
            - shared-signals-transmitter.transaction.account.gov.uk
            - !Sub ssf-transmitter.transaction.${Environment}.account.gov.uk
          HostedZoneId: !ImportValue SharedSignalsTransmitterApiPublicHostedZoneId
      ValidationMethod: DNS

  SharedSignalsTransmitterApiDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !If
        - IsProduction
        - shared-signals-transmitter.transaction.account.gov.uk
        - !Sub ssf-transmitter.transaction.${Environment}.account.gov.uk
      EndpointConfiguration:
        Types:
          - REGIONAL
      RegionalCertificateArn: !Ref SharedSignalsTransmitterApiCertificate
      SecurityPolicy: TLS_1_2

  SharedSignalsTransmitterApiAliasRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt SharedSignalsTransmitterApiDomainName.RegionalDomainName
        EvaluateTargetHealth: false
        HostedZoneId: !GetAtt SharedSignalsTransmitterApiDomainName.RegionalHostedZoneId
      HostedZoneId: !ImportValue SharedSignalsTransmitterApiPublicHostedZoneId
      Name: !Ref SharedSignalsTransmitterApiDomainName
      Type: A

  SharedSignalsTransmitterApiDomainNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: SharedSignalsTransmitterApiDomainName
      Type: String
      Value: !Ref SharedSignalsTransmitterApiDomainName

  #########################
  # SSF Cognito User Pool  #
  #########################

  SharedSignalsTransmitterCognitoCnameRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue SharedSignalsTransmitterApiPublicHostedZone
      Name: !If
        - IsProduction
        - auth.shared-signals-transmitter.transaction.account.gov.uk
        - !Sub auth.ssf-transmitter.transaction.${Environment}.account.gov.uk
      ResourceRecords:
        - !GetAtt SsfUserPoolDomain.CloudFrontDistribution
      Type: CNAME
      TTL: 300

  SsfUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      CustomDomainConfig:
        CertificateArn: '{{resolve:ssm:CognitoCustomDomainCertificateArn}}'
      Domain: !If
        - IsProduction
        - auth.shared-signals-transmitter.transaction.account.gov.uk
        - !Sub auth.ssf-transmitter.transaction.${Environment}.account.gov.uk
      UserPoolId: '{{resolve:ssm:SSFUserPoolId}}'

  CognitoDomainUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: CognitoDomainUrl
      Type: String
      Value: !Ref SsfUserPoolDomain
