AWSTemplateFormatVersion: '2010-09-09'

Description: |
  Creates the necessary DNS records, certificates and domain names for the query results and shared signals accounts

Parameters:
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - build
      - staging
      - integration
      - production

Conditions:
  IsProduction: !Equals
    - !Ref Environment
    - production
  IsBuild: !Equals
    - !Ref Environment
    - build

Resources:
  ZendeskWebhookApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !If
        - IsProduction
        - zendesk.transaction.account.gov.uk
        - !Sub 'zendesk.transaction.${Environment}.account.gov.uk'
      DomainValidationOptions:
        - DomainName: !If
            - IsProduction
            - zendesk.transaction.account.gov.uk
            - !Sub 'zendesk.transaction.${Environment}.account.gov.uk'
          HostedZoneId: !ImportValue ZendeskWebhookApiPublicHostedZoneId
      ValidationMethod: DNS

  ZendeskWebhookApiDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !If
        - IsProduction
        - zendesk.transaction.account.gov.uk
        - !Sub 'zendesk.transaction.${Environment}.account.gov.uk'
      EndpointConfiguration:
        Types:
          - REGIONAL
      RegionalCertificateArn: !Ref ZendeskWebhookApiCertificate
      SecurityPolicy: TLS_1_2

  ZendeskWebhookApiAliasRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt ZendeskWebhookApiDomainName.RegionalDomainName
        EvaluateTargetHealth: false
        HostedZoneId: !GetAtt ZendeskWebhookApiDomainName.RegionalHostedZoneId
      HostedZoneId: !ImportValue ZendeskWebhookApiPublicHostedZoneId
      Name: !Ref ZendeskWebhookApiDomainName
      Type: A

  ZendeskWebhookApiDomainNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: ZendeskWebhookApiDomainName
      Type: String
      Value: !Ref ZendeskWebhookApiDomainName

  # Mock server records
  MockServerCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: IsBuild
    Properties:
      DomainName: !Sub 'mockserver.transaction.${Environment}.account.gov.uk'
      DomainValidationOptions:
        - DomainName: !Sub 'mockserver.transaction.${Environment}.account.gov.uk'
          HostedZoneId: !ImportValue MockServerPublicHostedZoneId
      ValidationMethod: DNS

  MockServerDomainName:
    Type: AWS::ApiGateway::DomainName
    Condition: IsBuild
    Properties:
      DomainName: !Sub 'mockserver.transaction.${Environment}.account.gov.uk'
      EndpointConfiguration:
        Types:
          - REGIONAL
      RegionalCertificateArn: !Ref MockServerCertificate
      SecurityPolicy: TLS_1_2

  MockServerAliasRecord:
    Type: AWS::Route53::RecordSet
    Condition: IsBuild
    Properties:
      AliasTarget:
        DNSName: !GetAtt MockServerDomainName.RegionalDomainName
        EvaluateTargetHealth: false
        HostedZoneId: !GetAtt MockServerDomainName.RegionalHostedZoneId
      HostedZoneId: !ImportValue MockServerPublicHostedZoneId
      Name: !Ref MockServerDomainName
      Type: A

  MockServerDomainNameParameter:
    Condition: IsBuild
    Type: AWS::SSM::Parameter
    Properties:
      Name: MockServerDomainName
      Type: String
      Value: !Ref MockServerDomainName

  # Shared Signals Mock Receiver Api records
  SharedSignalsMockReceiverApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !If
        - IsProduction
        - shared-signals-mock-receiver.transaction.account.gov.uk
        - !Sub 'shared-signals-mock-receiver.transaction.${Environment}.account.gov.uk'
      DomainValidationOptions:
        - DomainName: !If
            - IsProduction
            - shared-signals-mock-receiver.transaction.account.gov.uk
            - !Sub 'shared-signals-mock-receiver.transaction.${Environment}.account.gov.uk'
          HostedZoneId: !ImportValue SharedSignalsMockReceiverApiPublicHostedZoneId
      ValidationMethod: DNS

  SharedSignalsMockReceiverApiDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !If
        - IsProduction
        - shared-signals-mock-receiver.transaction.account.gov.uk
        - !Sub 'shared-signals-mock-receiver.transaction.${Environment}.account.gov.uk'
      EndpointConfiguration:
        Types:
          - REGIONAL
      RegionalCertificateArn: !Ref SharedSignalsMockReceiverApiCertificate
      SecurityPolicy: TLS_1_2

  SharedSignalsMockReceiverApiAliasRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt SharedSignalsMockReceiverApiDomainName.RegionalDomainName
        EvaluateTargetHealth: false
        HostedZoneId: !GetAtt SharedSignalsMockReceiverApiDomainName.RegionalHostedZoneId
      HostedZoneId: !ImportValue SharedSignalsMockReceiverApiPublicHostedZoneId
      Name: !Ref SharedSignalsMockReceiverApiDomainName
      Type: A

  SharedSignalsMockReceiverApiDomainNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: SharedSignalsMockReceiverApiDomainName
      Type: String
      Value: !Ref SharedSignalsMockReceiverApiDomainName

  # Shared Signals Transmitter Api records
  SharedSignalsTransmitterApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !If
        - IsProduction
        - shared-signals-transmitter.transaction.account.gov.uk
        - !Sub 'shared-signals-transmitter.transaction.${Environment}.account.gov.uk'
      DomainValidationOptions:
        - DomainName: !If
            - IsProduction
            - shared-signals-transmitter.transaction.account.gov.uk
            - !Sub 'shared-signals-transmitter.transaction.${Environment}.account.gov.uk'
          HostedZoneId: !ImportValue SharedSignalsTransmitterApiPublicHostedZoneId
      ValidationMethod: DNS

  SharedSignalsTransmitterApiDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !If
        - IsProduction
        - shared-signals-transmitter.transaction.account.gov.uk
        - !Sub 'shared-signals-transmitter.transaction.${Environment}.account.gov.uk'
      EndpointConfiguration:
        Types:
          - REGIONAL
      RegionalCertificateArn: !Ref SharedSignalsTransmitterApiCertificate
      SecurityPolicy: TLS_1_2

  SharedSignalsTransmitterApiAliasRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt SharedSignalsTransmitterApiDomainName.RegionalDomainName
        EvaluateTargetHealth: false
        HostedZoneId: !GetAtt SharedSignalsTransmitterApiDomainName.RegionalHostedZoneId
      HostedZoneId: !ImportValue SharedSignalsTransmitterApiPublicHostedZoneId
      Name: !Ref SharedSignalsTransmitterApiDomainName
      Type: A

  SharedSignalsTransmitterApiDomainNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: SharedSignalsTransmitterApiDomainName
      Type: String
      Value: !Ref SharedSignalsTransmitterApiDomainName
