name: Package DNS records for Query Results account

on:
  push:
    branches:
      - main
    paths:
      - infrastructure/dns-records-query-results/**
  workflow_dispatch: {}

env:
  AWS_REGION: eu-west-2

jobs:
  package:
    name: Package template
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.QUERY_RESULTS_DNS_RECORDS_GH_ACTIONS_ROLE_ARN }}
      - name: Package SAM app
        uses: govuk-one-login/devplatform-upload-action@v3.8.1
        with:
          artifact-bucket-name: ${{ secrets.QUERY_RESULTS_DNS_RECORDS_ARTIFACT_BUCKET_NAME }}
          signing-profile-name: ${{ secrets.QUERY_RESULTS_SIGNING_PROFILE_NAME }}
          template-file: infrastructure/dns-records-query-results/template.yaml
          working-directory: .
