name: Validate templates, linting and tests

on:
  pull_request:
    branches:
      - main

jobs:
  validate-templates:
    name: Validate SAM templates
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install yamlfix
        run: pip install yamlfix
      - name: Run yamlfix
        run: yamlfix -c .yamlfix.toml --check .
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
      - name: Validate SAM templates
        run: ./scripts/validate-templates.sh
      - name: Run Checkov on SAM templates
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infrastructure/
          quiet: true
          framework: cloudformation
